/** Brother PEC 64-colour thread palette (index 0 = unused/unknown). */
export const PEC_THREADS: readonly string[] = [
  "Unknown",
  "Prussian Blue",
  "Blue",
  "Teal Green",
  "Corn Flower Blue",
  "Red",
  "Reddish Brown",
  "Magenta",
  "Light Lilac",
  "Lilac",
  "Mint Green",
  "Deep Gold",
  "Orange",
  "Yellow",
  "Lime Green",
  "Brass",
  "Silver",
  "Russet Brown",
  "Cream Brown",
  "Pewter",
  "Black",
  "Ultramarine",
  "Royal Purple",
  "Dark Gray",
  "Dark Brown",
  "Deep Rose",
  "Light Brown",
  "Salmon Pink",
  "Vermilion",
  "White",
  "Violet",
  "Seacrest",
  "Sky Blue",
  "Pumpkin",
  "Cream Yellow",
  "Khaki",
  "Clay Brown",
  "Leaf Green",
  "Peacock Blue",
  "Gray",
  "Warm Gray",
  "Dark Olive",
  "Linen",
  "Pink",
  "Deep Green",
  "Lavender",
  "Wisteria Violet",
  "Beige",
  "Carmine",
  "Amber Red",
  "Olive Green",
  "Dark Fuchsia",
  "Tangerine",
  "Light Blue",
  "Emerald Green",
  "Purple",
  "Moss Green",
  "Flesh Pink",
  "Harvest Gold",
  "Electric Blue",
  "Lemon Yellow",
  "Fresh Green",
  "Applique Material",
  "Applique Position",
  "Applique",
];

/** Janome JEF thread palette (index 0 = unused/unknown). */
export const JEF_THREADS: readonly string[] = [
  "Unknown",
  "Black",
  "White",
  "Yellow",
  "Orange",
  "Olive Green",
  "Green",
  "Sky",
  "Purple",
  "Pink",
  "Red",
  "Brown",
  "Blue",
  "Gold",
  "Dark Brown",
  "Pale Violet",
  "Pale Yellow",
  "Pale Pink",
  "Peach",
  "Beige",
  "Wine Red",
  "Pale Sky",
  "Yellow Green",
  "Silver Gray",
  "Gray",
  "Pale Aqua",
  "Baby Blue",
  "Powder Blue",
  "Bright Blue",
  "Slate Blue",
  "Navy Blue",
  "Salmon Pink",
  "Coral",
  "Burnt Orange",
  "Cinnamon",
  "Umber",
  "Blonde",
  "Sunflower",
  "Orchid Pink",
  "Peony Purple",
  "Burgundy",
  "Royal Purple",
  "Cardinal Red",
  "Opal Green",
  "Moss Green",
  "Meadow Green",
  "Dark Green",
  "Aquamarine",
  "Emerald Green",
  "Peacock Green",
  "Dark Gray",
  "Ivory White",
  "Hazel",
  "Toast",
  "Salmon",
  "Cocoa Brown",
  "Sienna",
  "Sepia",
  "Dark Sepia",
  "Violet Blue",
  "Blue Ink",
  "Solar Blue",
  "Green Dust",
  "Crimson",
  "Floral Pink",
  "Wine",
  "Olive Drab",
  "Meadow",
  "Mint",
  "Canary Yellow",
  "Vermilion",
  "Marigold",
  "Turquoise",
  "Blue Grass",
  "Ivory",
  "Zinc",
  "Cream",
  "Steel Blue",
  "Winter Green",
];

/** Resolves a thread name to a palette index; falls back to cycling. */
export const paletteIndex = (
  palette: readonly string[],
  name: string | undefined,
  position: number,
) => {
  const wanted = name?.trim().toLowerCase();
  if (wanted) {
    const found = palette.findIndex(
      (entry, index) => index > 0 && entry.toLowerCase() === wanted,
    );
    if (found > 0) return found;
  }
  // Skip index 0 and wrap inside the palette.
  return 1 + (position % (palette.length - 1));
};

export const paletteName = (palette: readonly string[], index: number) =>
  palette[index] ?? `Thread ${index}`;
